# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dayofweek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=20)),
                ('slot_1', models.CharField(max_length=100)),
                ('slot_2', models.CharField(max_length=100)),
                ('slot_3', models.CharField(max_length=100)),
                ('slot_4', models.CharField(max_length=100)),
                ('slot_5', models.CharField(max_length=100)),
                ('slot_6', models.CharField(max_length=100)),
            ],
        ),
    ]
